import streamlit as st
from gtts import gTTS
from streamlit_mic_recorder import speech_to_text
import os
import time
import base64

# --- 1. PAGE CONFIGURATION ---
st.set_page_config(
    page_title="FRIDAY AI",
    page_icon="🧿",
    layout="wide",
    initial_sidebar_state="collapsed"
)

# --- 2. SESSION STATE MANAGEMENT ---
if 'chat_history' not in st.session_state:
    st.session_state.chat_history = [
        {"role": "assistant", "content": "System Online. I am Friday. I am listening... State your request."}
    ]
if 'booking_step' not in st.session_state:
    st.session_state.booking_step = 0
if 'booking_data' not in st.session_state:
    st.session_state.booking_data = {"guests": "TBD", "type": "TBD", "view": "TBD"}
if 'system_initialized' not in st.session_state:
    st.session_state.system_initialized = False

# --- 3. ULTRA-FUTURISTIC CSS ---
st.markdown("""
<style>
    /* --- BACKGROUND --- */
    .stApp {
        background: linear-gradient(rgba(0,0,0,0.8), rgba(10,20,30,0.9)), 
                    url('https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=2070&auto=format&fit=crop');
        background-size: cover;
        background-attachment: fixed;
        font-family: 'Segoe UI', sans-serif;
        color: white;
    }

    /* --- THE ORB (Recorder Button) --- */
    /* This targets the specific button generated by the recorder */
    div.stButton > button:first-child {
        background: radial-gradient(circle, #00f2ff 0%, #003344 100%);
        border: 2px solid #00f2ff;
        color: white;
        font-weight: bold;
        border-radius: 50%;
        height: 120px;
        width: 120px;
        font-size: 20px;
        box-shadow: 0 0 20px #00f2ff;
        transition: all 0.3s ease;
        margin: 0 auto;
        display: block;
    }

    /* Hover Glow */
    div.stButton > button:first-child:hover {
        box-shadow: 0 0 60px #00f2ff, 0 0 100px #00f2ff inset;
        transform: scale(1.05);
    }

    /* Recording State (Red) */
    div.stButton > button:active {
        background: radial-gradient(circle, #ff0055 0%, #440011 100%);
        box-shadow: 0 0 60px #ff0055;
        border-color: #ff0055;
    }

    /* --- CHAT BUBBLES --- */
    .stChatMessage {
        background: rgba(0, 0, 0, 0.6);
        border: 1px solid #333;
        border-radius: 15px;
    }

    /* --- STATUS BAR --- */
    .status-bar {
        color: #00f2ff;
        text-align: center;
        font-family: 'Courier New', monospace;
        letter-spacing: 3px;
        margin-bottom: 20px;
        text-shadow: 0 0 10px #00f2ff;
    }

    #MainMenu {visibility: hidden;}
    footer {visibility: hidden;}
    header {visibility: hidden;}
</style>
""", unsafe_allow_html=True)


# --- 4. AUDIO ENGINE (Hidden Autoplay) ---
def play_audio(text):
    """Generates audio and forces the browser to play it."""
    try:
        audio_file = f"friday_voice_{int(time.time())}.mp3"
        # 'co.uk' = British accent (Friday Style)
        tts = gTTS(text=text, lang='en', tld='co.uk')
        tts.save(audio_file)

        with open(audio_file, "rb") as f:
            audio_bytes = f.read()

        b64 = base64.b64encode(audio_bytes).decode()

        # Invisible HTML Player
        md = f"""
            <audio autoplay="true">
            <source src="data:audio/mp3;base64,{b64}" type="audio/mp3">
            </audio>
            """
        st.markdown(md, unsafe_allow_html=True)
        os.remove(audio_file)
    except Exception:
        pass


# --- 5. CONVERSATION LOGIC ---
def core_logic(text_input):
    text = text_input.lower()
    step = st.session_state.booking_step

    # INTERRUPT COMMANDS
    if any(x in text for x in ["reset", "cancel", "stop"]):
        st.session_state.booking_step = 0
        st.session_state.booking_data = {k: "TBD" for k in st.session_state.booking_data}
        return "Protocols cleared. Standing by."

    # STEP 0: GREETING
    if step == 0:
        if any(x in text for x in ["book", "room", "hi", "hello"]):
            st.session_state.booking_step = 1
            return "Acknowledged. Initiating reservation. State the number of guests."
        return "I am Friday. Say 'Book a room' to begin."

    # STEP 1: GUESTS
    elif step == 1:
        import re
        nums = re.findall(r'\d+', text)
        # Text-to-number mapping
        map_w = {"one": "1", "two": "2", "three": "3", "four": "4", "five": "5"}
        for k, v in map_w.items():
            if k in text: nums.append(v)

        if nums:
            st.session_state.booking_data['guests'] = nums[0]
            st.session_state.booking_step = 2
            return f"{nums[0]} guests registered. Select classification: AC or Non-AC?"
        return "Numeric input required. How many guests?"

    # STEP 2: TYPE
    elif step == 2:
        if "non" in text:
            st.session_state.booking_data['type'] = "Non-AC"
            st.session_state.booking_step = 3
            return "Non-AC confirmed. Select upgrade: Balcony or Pool Access?"
        elif "ac" in text:
            st.session_state.booking_data['type'] = "AC"
            st.session_state.booking_step = 3
            return "AC confirmed. Select upgrade: Balcony or Pool Access?"
        return "Binary choice required. AC or Non-AC?"

    # STEP 3: VIEW
    elif step == 3:
        if "pool" in text:
            st.session_state.booking_data['view'] = "Pool Access"
        else:
            st.session_state.booking_data['view'] = "Balcony"

        st.session_state.booking_step = 4
        return f"Configuration complete. {st.session_state.booking_data['type']} room with {st.session_state.booking_data['view']}. Authorize?"

    # STEP 4: CONFIRM
    elif step == 4:
        if any(x in text for x in ["yes", "confirm", "ok", "sure"]):
            st.balloons()
            st.session_state.booking_step = 0
            return "Transaction verified. Reservation uploaded. Goodbye."
        else:
            st.session_state.booking_step = 0
            return "Transaction aborted."

    return "Input unclear. Please repeat."


# --- 6. UI LAYOUT ---

# SCENE 1: SYSTEM BOOT (This fixes the audio permission issue)
if not st.session_state.system_initialized:
    st.markdown("<br><br><br>", unsafe_allow_html=True)
    st.markdown("<h1 style='text-align: center; color: #00f2ff; font-size: 60px;'>FRIDAY AI</h1>",
                unsafe_allow_html=True)
    st.markdown("<p style='text-align: center; color: white; letter-spacing: 2px;'>VOICE PROTOCOLS OFFLINE</p>",
                unsafe_allow_html=True)

    c1, c2, c3 = st.columns([1, 1, 1])
    with c2:
        st.markdown("<br>", unsafe_allow_html=True)
        # User MUST click this to allow browser audio
        if st.button("INITIALIZE SYSTEM", use_container_width=True):
            st.session_state.system_initialized = True
            st.rerun()

# SCENE 2: MAIN INTERFACE
else:
    # --- SIDEBAR (STATUS) ---
    with st.sidebar:
        st.title("STATUS MONITOR")
        st.markdown("---")
        st.write(f"**SYSTEM INTEGRITY: {st.session_state.booking_step * 25}%**")
        st.progress(min(st.session_state.booking_step * 25, 100))
        st.divider()
        st.metric("GUESTS", st.session_state.booking_data['guests'])
        st.metric("TYPE", st.session_state.booking_data['type'])
        st.metric("VIEW", st.session_state.booking_data['view'])
        st.divider()
        if st.button("REBOOT SYSTEM", use_container_width=True):
            st.session_state.clear()
            st.rerun()

    # --- MAIN AREA ---
    st.markdown("<h2 style='text-align: center; color: #00f2ff;'>SIMPLOTEL AI CONCIERGE</h2>", unsafe_allow_html=True)
    st.markdown("<div class='status-bar'>VOICE INTERFACE ACTIVE</div>", unsafe_allow_html=True)

    # Chat Display
    chat_box = st.container(height=350)
    with chat_box:
        for msg in st.session_state.chat_history:
            with st.chat_message(msg['role']):
                st.write(msg['content'])

    # --- THE INTERFACE ---
    st.markdown("<br>", unsafe_allow_html=True)
    c1, c2, c3 = st.columns([1, 1, 1])

    with c2:
        # This creates the ORB button.
        # 'start_prompt' is the resting Orb. 'stop_prompt' is the recording Red Orb.
        # It processes immediately upon stopping.
        voice_text = speech_to_text(
            language='en',
            start_prompt="🧿",
            stop_prompt="🔴",
            just_once=True,
            key='voice_orb',
            callback=None
        )
        st.markdown("<p style='text-align: center; color: #aaa; font-size: 12px;'>TAP TO SPEAK • TAP TO STOP</p>",
                    unsafe_allow_html=True)

    # --- TEXT FALLBACK ---
    text_input = st.chat_input("Or type here...")

    # --- PROCESSING ---
    final_input = voice_text if voice_text else text_input

    if final_input:
        # 1. User
        st.session_state.chat_history.append({"role": "user", "content": final_input})

        # 2. Logic
        bot_reply = core_logic(final_input)
        st.session_state.chat_history.append({"role": "assistant", "content": bot_reply})

        # 3. Audio
        play_audio(bot_reply)

        # 4. Refresh to show result
        time.sleep(0.5)
        st.rerun()

    # --- PLAY WELCOME MESSAGE (ONCE) ---
    # This runs immediately after you click "Initialize System"
    if len(st.session_state.chat_history) == 1 and st.session_state.system_initialized:
        # We check if we just initialized to play the intro
        # We use a dirty check on the last message content
        if "System Online" in st.session_state.chat_history[0]['content']:
            # Only play if we haven't said anything else
            pass  # The logic is handled by the standard flow if we trigger it manually,
            # but to force the FIRST greeting audio:

            # Create a one-time trigger in session state to avoid looping audio
            if 'intro_played' not in st.session_state:
                play_audio("System Online. I am Friday. I am listening... State your request.")
                st.session_state.intro_played = True